spring:
  cloud:
    kubernetes:
      config:
        enabled: true
        sources:
          - namespace: my-namespace
            name: config-example
      reload:
        enabled: true
        mode: event
        strategy: restart
        period: 5